language: node_js

matrix:
  include:
    - os: linux
      node_js: 'v6.9.0'

    - os: linux
      node_js: 'v6.17.1'

    - os: linux
      node_js: 'v8.16.0'

    - os: linux
      node_js: 'v10.16.0'

    - os: linux
      node_js: 'v12.6.0'

    - os: windows
      node_js: 'v12.6.0'

    - os: osx
      node_js: 'v12.6.0'

cache:
  directories:
    - 'node_modules'

script:
  - npm run clean
  - npm run lint
  - npm run build
  - npm run test
