name: main

on: push

jobs:
  build:
    strategy:
      matrix:
        config:
          - runs-on: ubuntu-20.04
            node-version: '6.9.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1
            NO_NPM_CI: 1

          - runs-on: ubuntu-20.04
            node-version: '8.9.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1
            NO_NPM_CI: 1

          - runs-on: ubuntu-20.04
            node-version: '10.13.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1

          - runs-on: ubuntu-20.04
            node-version: '12.13.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1

          - runs-on: ubuntu-20.04
            node-version: '14.15.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1

          - runs-on: ubuntu-20.04
            node-version: '16.13.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1

          - runs-on: ubuntu-20.04
            node-version: '18.12.0' # LTS

          - runs-on: ubuntu-20.04
            node-version: '18.17.1' # LTS (current)

          - runs-on: ubuntu-20.04
            node-version: '20.5.1'

          - runs-on: windows-2019
            node-version: '20.5.1'

          - runs-on: macos-10.15
            node-version: '20.5.1'

    runs-on: ${{ matrix.config.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.config.node-version }}

      - name: Dependencies
        run: npm ci
        if: matrix.config.NO_NPM_CI != 1

      - name: Dependencies
        run: npm install
        if: matrix.config.NO_NPM_CI == 1

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint
        if: matrix.config.NO_LINT != 1

      - name: Formatted
        run: npm run formatted
        if: matrix.config.NO_FORMATTED != 1

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          registry-url: https://registry.npmjs.org/

      - name: Dependencies
        run: npm ci

      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
